### ISSUE TITLE
Question on add-changelog-snippet action

### ISSUE THREAD

**Issue by jwodder** [datalad/release-action#3]
@yarikoptic The add-changelog-snippet workflow in DataLad is tightly coupled to both the names used for the semver labels and the CHANGELOG category names (i.e., the headers used in autogenerated changelog fragments have to be spelled the same way as the categories listed in the project's `scriv.ini`).  How should the action handle this so that it's generic enough for use by other projects?

**Comment by yarikoptic** [comment]
Probably `scriv` needs them only for `scriv new`. We can leave it to the user (or provide a helper later on) to define them if `scriv new` to be used "manually".  Otherwise, for the labels consideration etc, let's make them configurable and also sections configurable (optionally) as a list of categories, e.g.

```
categories:
  - name: Breaking Changes
    version-boost: minor   # for DataLad, typically "major" ;)
    label: semver-major
  - name: Enhancements and New Features
    version-boost: minor
    label: semver-minor
  - name: Bug Fixes
    version-boost: patch
    label: semver-patch
 - name: Dependencies
 - name: Documentation
   label: semver-documentation
 ...
```

defaulting to `version-boost: patch` and if no `label` is  specified - would mean that no label in github could trigger pre-generation of that section but it could be added manually anyways (like any other I guess).

With all that I feel like we circling back and this "action" should primarily, as `auto` implemented as a tool, with those settings residing e.g. in `.datalad-release-action.yaml` config file, with action just stating which step todo (`release`, `add-changelog-snippet`).

**Comment by jwodder** [comment]
@yarikoptic 

> With all that I feel like we circling back and this "action" should primarily, as auto implemented as a tool, with those settings residing e.g. in `.datalad-release-action.yaml` config file, with action just stating which step todo (`release`, `add-changelog-snippet`).

Is this something you actually want me to do, or are you just thinking out loud?

**Comment by yarikoptic** [comment]
yes, let's make it a work item:  implement all logic as a script `datalad-release-action` which would implement commands `release` and `add-changelog-snippet` while consulting to `.datalad-release-action.yaml` config file.

**Comment by jwodder** [comment]
@yarikoptic Where should this script live?  I'm not entirely certain whether actions in subdirectories can access files elsewhere in the repo.

**Comment by yarikoptic** [comment]
script will live in this repository (like scripts live in https://github.com/datalad/datalad-action/tree/main/get/scripts etc). That action of cause would require first `checkout` action to be ran so it ends up having access to the files in the repo it is intended to run on.  So if (following https://github.com/datalad/datalad-action/blob/main/install/action.yaml as an example) e.g. there would be usage in e.g. data-core like

```
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
... more relevant like setting up git ...
      - name: Release DataLad
        uses: datalad/release-action/release
```

then there would be a `release/` folder in this repo with `action.yaml` under it which would have smth like

```
runs:
  using: "composite"
  steps:
    - name: Release
      run: ${{ github.action_path }}/../datalad-release-action release
      shell: bash
```
which would have access to the checkout of datalad core where it would consult to `.datalad-release-action.yaml`.

**Comment by jwodder** [comment]
@yarikoptic Yes, but are you sure that `uses: datalad/release-action/release` would clone the entirety of `datalad/release-action` and not just the `release/` directory?  I tried Googling this and couldn't find anything.

**Comment by yarikoptic** [comment]
dunno -- I would have just tried and see. if not -- I am not even sure if we need `/subaction` like `/release` or we could just use e.g.

```
- name: Release DataLad
  uses: datalad/release-action
  with:
      args: ['release']
```
and pass those args into the CLI thus just making action a convenient way to expose the CLI.

**Comment by jwodder** [comment]
@yarikoptic Question: Where should the Git author name & e-mail be configured — in the `.datalad-release-action.yaml` config file, as action inputs, as a separate step that the user of the action must add to their workflow, or elsewhere?  For the "add-changelog-snippet" action, things would be much simpler if the author details did not have to be read from the config file (as they're only used by a sequence of Bash commands that would best be left as-is instead of invoked via Python).

**Comment by yarikoptic** [comment]
Nice question/aspect. Since when used locally should use local user configuration, IMHO shouldn't be in the `.datalad-release-action.yaml` config file.  I would say: make it options for the action, but also default to some sensible default such as the name/email we use in the action already.

**Comment by yarikoptic** [comment]
well, I was hoping that we could absorb as much as possible of logic so there is minimal boiler-plate left in the workflows we need to copy into each repository. I am not sure we should provision for some alternative ways to trigger it ATM.  So I thought it would be nice if minimal workflow to become smth like 

```yaml
name: Add changelog.d snippet

on:
  pull_request_target:
    # "labeled" is also triggered when a PR is created with one or more labels
    types: [synchronize, labeled]

# Prevent the workflow from running multiple jobs at once when a PR is created
# with multiple labels:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  add:
    runs-on: ubuntu-latest
    if: >
      github.repository_owner == 'datalad'
        && contains(github.event.pull_request.labels.*.name, 'CHANGELOG-missing')
    steps:
      - name: Add changelog.d snippet and remove the label
        uses: datalad/release-action/add-changelog-entry
        with:  # all optional
          labels: CHANGELOG-missing  # optional and typically not specified
          token: ${{ secrets.GITMATE_GITHUB_TOKEN }}
```

is that possible? or action would not have easy access to other actions/metadata (for checkout etc)?

NB I guess the `if` can't be nicely handled by the action.
